name: 'ecma-262'

on:
  pull_request_target:
    branches:
       - '*'
  push:
    branches:
       - main

jobs:
  build:
    name: 'check IPR form'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: git log -2 ${{ github.head_ref || 'HEAD' }}
      - run: node scripts/ipr-check.js tc39/source-map-spec ${{ github.head_ref || 'HEAD' }}
        env:
          GH_TOKEN: ${{ secrets.GH_IPR_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
